### ISSUE TITLE
No template for running query

### ISSUE THREAD

**Issue by YehorManevych** [atifaziz/LinqPadless#27]
Hi
I've tried to run:
`.\lpless test.linq` 
And I got 
`No template for running query.`
It wasn't clear from the documentation what this error meant, so I did some debugging and discovered that lpless searches for .csproj and .cs files. So I created a template project at `.\.lpless\templates\template` with a file `Main.cs`. But lpless just executed this template program. I found that it tries to match something with regex [inside this method](https://github.com/linqpadless/LinqPadless/blob/1ef8f4f99927d121064d41dfffa96e66bcf32f33/src/Program.cs#L852), but in my case it wasn't able to find any matches, so program remained unchanged. 
What am I missing here?

**Comment by atifaziz** [comment]
The architecture of LINQPadless has changed considerably with version 2, which is still un-released and what you're looking at in the master branch. I haven't had the time to publish a template and document how they work (though I am not far). If you're just looking to work with version 1, you'll find it in the [1.x](https://github.com/linqpadless/LinqPadless/tree/1.x) branch or just use the [1.1.0](https://github.com/linqpadless/LinqPadless/releases/tag/v1.1.0) release.

LINQPadless 2 drops support for .NET Framework, which was not an easy decision but [that's the direction of the platform](https://devblogs.microsoft.com/dotnet/introducing-net-5/). If you're fine with that then stay tuned and I'll drop a note here when a template has been published.

Meanwhile, nice to see you weren't afraid to dig in and poke around. I've [attached a copy of the template][template.zip] as I have it worked right now if you want to play with version 2. You'll notice that the template isn't very straightforward, but that's because the signature for C#'s `Main` has gotten quite complicated over years:

         [ static ] ( void | int | Task | Task<int> ) Main([ string[] args ])

This gives 16 combinations, as can be seen from the table below:

| Signature                                | Symbols                          |
|------------------------------------------|----------------------------------|
| `static void Main()`                     | `STATIC`, `VOID`                 |
| `static int Main()`                      | `STATIC`,                        |
| `static void Main(string[] args)`        | `STATIC`, `VOID`, `ARGS`         |
| `static int Main(string[] args)`         | `STATIC`, `ARGS`                 |
| `static Task Main()`                     | `STATIC`, `VOID`, `TASK`         |
| `static Task<int> Main()`                | `STATIC`, `TASK`                 |
| `static Task Main(string[] args)`        | `STATIC`, `VOID`, `TASK`, `ARGS` |
| `static Task<int> Main(string[] args)`   | `STATIC`, `TASK`, `ARGS`         |
| `void Main()`                            | `VOID`                           |
| `int Main()`                             |                                  |
| `void Main(string[] args)`               | `VOID`, `ARGS`                   |
| `int Main(string[] args)`                | `ARGS`                           |
| `Task Main()`                            | `VOID`, `TASK`                   |
| `Task<int> Main()`                       | `TASK`                           |
| `Task Main(string[] args)`               | `VOID`, `TASK`, `ARGS`           |
| `Task<int> Main(string[] args)`          | `TASK`, `ARGS`                   |

Depending on the signature you used for a program query in LINQPad, LINQPadless defines conditional compilation symbols (right column) to drive and select the appropriate signature when fusing the template with your code.

You can use the same template project for all types of queries: expression, statements, program.

There are some place holders (`{% … %}`) that get replaced with the actual code from the source query. The main place holders are: `expression`, `statements`, `program`, `program-types` and `imports`.

---
📎 [`template.zip`][template.zip]

[template.zip]: https://github.com/linqpadless/LinqPadless/files/3505821/template.zip

**Comment by YehorManevych** [comment]
It worked! The only change I had to make was adding `<LangVersion>latest</LangVersion>` to the .csproj file. That was necessary to allow usage of async Main.
Thanks a lot for sharing the template!

**Comment by atifaziz** [comment]
> It worked! 

Glad to hear and thanks for sharing your feedback. By the way, [I'm publishing the template now to its repo](https://github.com/atifaziz/LinqPadlessProgramTemplate).

**Comment by atifaziz** [comment]
> The only change I had to make was adding `<LangVersion>latest</LangVersion>` to the .csproj file. That was necessary to allow usage of async Main.

Surprised to hear because that case should be covered without specifying the `LangVersion` element in the project file.

**Comment by atifaziz** [comment]
> The only change I had to make was adding `<LangVersion>latest</LangVersion>` to the .csproj file. That was necessary to allow usage of async Main.

Surprised to hear because that case should be covered without specifying the `LangVersion` element in the project file.
