### ISSUE TITLE
System doesn't use LINQPad nuget manager specifing version

### ISSUE THREAD

**Issue by shps951023** [atifaziz/LinqPadless#44]
> LINQPadLess version is 1.1

If LINQPad Nuget Manager specify  Dapper 1.6 version (lowest .net version support 4.5.1)
![image](https://user-images.githubusercontent.com/12729184/83990004-c6860e80-a97a-11ea-9cb0-6c61cd52a025.png)

but when i command `lpless -t exe "path"`  system using nuget `latest` Dapper 2.0.35 version,and it `doesn't` support .net v4.5.2.

![image](https://user-images.githubusercontent.com/12729184/83990080-05b45f80-a97b-11ea-8180-d541e1122bf5.png)

---

### edited : 

Even i edit .linq file and specifing the nuget version,it still not work.
![image](https://user-images.githubusercontent.com/12729184/83991300-e3bcdc00-a97e-11ea-982e-5bcc3f246245.png)

**Comment by atifaziz** [comment]
When you add the NuGet package reference in the UI, you have to use the **Add Specific Version To Query** menu option as show below:

![image](https://user-images.githubusercontent.com/20511/84002147-3d65dc00-a968-11ea-9c80-406b55bfe875.png)

Once you've selected version 1.60.6, you'll see it appear in the list on the left with a special note about the version-specific reference:

![image](https://user-images.githubusercontent.com/20511/84002242-69815d00-a968-11ea-9681-04d8a362d9f7.png)

You'll also see the version number appear in the **Additional Reference** tab of the **Query Properties** dialog (F4):

![image](https://user-images.githubusercontent.com/20511/84002335-8f0e6680-a968-11ea-9df8-b1d8f64b0a1d.png)

In the query file, the reference appears as:

```xml
<NuGetReference Version="1.60.6">Dapper</NuGetReference>
```

In your case, you added the version number to the wrong element; you added it to the `Namespace` element instead of the `NuGetReference` element for Dapper.

So assuming a `DapperQuery.linq` with the following content:

```
<Query Kind="Expression">
  <NuGetReference Version="1.60.6">Dapper</NuGetReference>
</Query>

Dapper.DbString.DefaultLength
```

Running `lpless.exe -t exe .DapperQuery.linq` should use the specified version and compile successfully:

```
Q:\DapperQuery.linq
  Packages directory: Q:\packages
  Packages target: .NETFramework,Version=v4.5.2
  Resolving references...
    Dapper 1.60.6
  Resolved references (1):
    packages\Dapper.1.60.6\lib\net451\Dapper.dll
  Q:\tools\Microsoft.Net.Compilers\tools\csc.exe Q:\DapperQuery.cs /r:System.dll /r:Microsoft.CSharp.dll /r:System.Core.dll /r:System.Data.dll /r:System.Data.Entity.dll /r:System.Transactions.dll /r:System.Xml.dll /r:System.Xml.Linq.dll /r:System.Data.Linq.dll /r:System.Drawing.dll /r:System.Data.DataSetExtensions.dll /r:packages\Dapper.1.60.6\lib\net451\Dapper.dll
    Microsoft (R) Visual C# Compiler version 2.0.0.61501
    Copyright (C) Microsoft Corporation. All rights reserved.
```

I'm going to close this as a non-issue.

**Comment by shps951023** [comment]
@atifaziz  thanks,it's helpful!
